export const SET_CONFIG = Symbol.for(':mvar/set-config')
export const OBJECT_REST_REF = Symbol.for(':mvar/object-rest-ref')
export const SYMBOL = Symbol.for(':mvar/symbol')
export const CONFIG = Symbol.for(':mvar/config')
export const EMIT = Symbol.for(':mvar/emit')
export const MVAR = Symbol.for(':mvar')
export const OPERATIONS = Symbol.for(':mvar/operations')